// flow-typed signature: fe61f286ae22731ea848281e07705fb8
// flow-typed version: <<STUB>>/gulp-clean_v^0.4.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-clean'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-clean' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-clean/test' {
  declare module.exports: any;
}

declare module 'gulp-clean/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-clean/index' {
  declare module.exports: $Exports<'gulp-clean'>;
}
declare module 'gulp-clean/index.js' {
  declare module.exports: $Exports<'gulp-clean'>;
}
declare module 'gulp-clean/test.js' {
  declare module.exports: $Exports<'gulp-clean/test'>;
}
declare module 'gulp-clean/utils.js' {
  declare module.exports: $Exports<'gulp-clean/utils'>;
}
