export const ADD_TODO = 'ADD_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_COMPLETED_TODOS = 'DELETE_COMPLETED_TODOS';
export const TOGGLE_ALL_TODOS = 'TOGGLE_ALL_TODOS';

export const APPLY_FILTER = 'APPLY_FILTER';
